cartesian_servo_node:
  ros__parameters:
    # FR3机器人URDF
    urdf_path: "/home/harry/franka_ros2_ws/src/franka_python/config/urdf/fr3.urdf"

    # 末端执行器坐标系
    end_effector_frame: "fr3_hand_tcp"

    # 阻尼最小二乘参数
    damping: 0.05

    # 控制频率
    publish_rate_hz: 50.0

    # 0.0表示持续运行
    duration_sec: 0.0

    # true只计算和打印，false真实发送
    dry_run: true

    # ROS topics
    joint_state_topic: "/franka/joint_states"
    command_topic: "/velocity_command_node/target_velocities"
    visual_velocity_topic: "/visual_servo_velocity"

    # 单关节速度限幅
    max_joint_velocity: 0.05

    # 视觉速度超时时间
    visual_velocity_timeout_sec: 0.2

    # 末端执行器到相机的变换矩阵
    T_end_effector_camera: [
      1.0, 0.0, 0.0, 0.0,
      0.0, 1.0, 0.0, 0.0,
      0.0, 0.0, 1.0, 0.0,
      0.0, 0.0, 0.0, 1.0
    ]


visual_servo_law:
  ros__parameters:
    # 相机内参
    fx: 891.1
    fy: 879.2
    cx: 266.8
    cy: 200.8

    # 目标球参数
    sphere_radius: 0.01

    # 异常情况下的备用深度
    initial_depth: 0.5

    # 期望视觉特征
    desired_u: 320.0
    desired_v: 240.0
    desired_radius: 30.0

    # IBVS增益，控制误差转化成速度的比例，大小影响收敛速度和稳定性
    lambda_gain: 0.001

    # 输出topic
    visual_velocity_topic: "/visual_servo_velocity"